- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: create environment variables from template
      template:
        src: templates/prod.env.js2
        dest: ~/prod.env

    - name: run container
      community.docker.docker_container:
        name: some-redmine
        recreate: yes
        image: redmine
        state: started
        ports: 8080:3000
        env_file:
            '~/prod.env'
