- hosts: all
  become: true
  gather_facts: no

  tasks:
    - name: create environment variables from template
      template:
        src: templates/prod.env.js2
        dest: ~/prod.env

    - name: Install packages for
      ansible.builtin.apt:
        name: python3-pip
        update_cache: yes

    - name: Install Docker Module for Python
      ansible.builtin.pip:
        name: docker

    - name: run container
      community.docker.docker_container:
        name: some-redmine
        recreate: yes
        image: redmine
        state: started
        ports: 8080:3000
        env_file:
            '~/prod.env'
